<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Creative Palace</title>
	<link rel="icon" href="#agkt{baseUrl}/assets/img/favicon.ico">
	<link rel="stylesheet" type="text/css" href="#agkt{baseUrl}/assets/library/bootstrap/bootstrap.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="#agkt{baseUrl}/assets/css/style.css">
</head>
<body>
<header>
	<div class="container">
		<div class="row">
			<div class="col-4 text-left">
				<div class="logo">
					<a href="index"><img src="#agkt{baseUrl}/assets/img/logo.png"></a>
				</div> <!-- .logo -->
			</div> <!-- .col-4 .text-left -->
		</div> <!-- .row -->
	</div> <!-- .container -->
</header>